<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>py18_2019_06_25_23_23_28_report</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

    <style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }

    </style>

</head>
<body>
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}

</script>
<div class='heading'>
    <h1 style="font-family: Microsoft YaHei">py18_2019_06_25_23_23_28_report</h1>
    <p class='attribute'><strong>测试人员 : </strong> july</p>
    <p class='attribute'><strong>开始时间 : </strong> 2019-06-25 23:23:31</p>
    <p class='attribute'><strong>合计耗时 : </strong> 0:00:00.351020</p>
    <p class='attribute'><strong>测试结果 : </strong> 共 8，错误 8，通过率= 0.00%</p>

    <p class='description'>参数化报告</p>
</div>


<p id='show_detail_line'>
    <a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 0.00% }</a>
    <a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 0 }</a>
    <a class="btn btn-success" href='javascript:showCase(2)'>通过{ 0 }</a>
    <a class="btn btn-info" href='javascript:showCase(3)'>所有{ 8 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
    <colgroup>
        <col align='left'/>
        <col align='right'/>
        <col align='right'/>
        <col align='right'/>
        <col align='right'/>
        <col align='right'/>
    </colgroup>
    <tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
        <td>用例集/测试用例</td>
        <td>总计</td>
        <td>通过</td>
        <td>失败</td>
        <td>错误</td>
        <td>详细</td>
    </tr>

    <tr class='errorClass warning'>
        <td>unittest.loader._FailedTest</td>
        <td class="text-center">4</td>
        <td class="text-center">0</td>
        <td class="text-center">0</td>
        <td class="text-center">4</td>
        <td class="text-center"><a href="javascript:showClassDetail('c1',4)" class="detail" id='c1'>详细</a></td>
    </tr>

    <tr id='ft1_1' class='none'>
        <td class='errorCase'>
            <div class='testcase'>case_add</div>
        </td>
        <td colspan='5' align='center'>
            <!--默认收起错误信息 -Findyou
            <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
            <div id='div_ft1_1' class="collapse">  -->
            <!-- 默认展开错误信息 -Findyou -->
            <button id='btn_ft1_1' type="button" class="btn btn-danger btn-xs" data-toggle="collapse"
                    data-target='#div_ft1_1'>错误
            </button>
            <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: ImportError: Failed to import test module: case_add
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\testcase\case_add.py", line 21, in &lt;module&gt;
    my_generate.generate(file_path, sheet_name, yaml_file=f'{CONF_DIR}parms.yaml')
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\common\generate.py", line 83, in generate
    self.origin_data = R_r_excel.ReadExcel(file_path, sheet_name)
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\common\R_r_excel.py", line 27, in __init__
    wb = openpyxl.load_workbook(file_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\openpyxl\reader\excel.py", line 311, in load_workbook
    data_only, keep_links)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\openpyxl\reader\excel.py", line 126, in __init__
    self.archive = _validate_archive(fn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\openpyxl\reader\excel.py", line 96, in _validate_archive
    raise InvalidFileException(msg)
openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support  file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm



    </pre>
            </div>
        </td>
    </tr>

    <tr id='ft1_2' class='none'>
        <td class='errorCase'>
            <div class='testcase'>case_bidLoan</div>
        </td>
        <td colspan='5' align='center'>
            <!--默认收起错误信息 -Findyou
            <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
            <div id='div_ft1_2' class="collapse">  -->
            <!-- 默认展开错误信息 -Findyou -->
            <button id='btn_ft1_2' type="button" class="btn btn-danger btn-xs" data-toggle="collapse"
                    data-target='#div_ft1_2'>错误
            </button>
            <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: ImportError: Failed to import test module: case_bidLoan
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\testcase\case_bidLoan.py", line 20, in &lt;module&gt;
    my_generate = Generate(file_path, sheet_name, yaml_file=f'{CONF_DIR}parms.yaml')
TypeError: __init__() got an unexpected keyword argument 'yaml_file'



    </pre>
            </div>
        </td>
    </tr>

    <tr id='ft1_3' class='none'>
        <td class='errorCase'>
            <div class='testcase'>case_recharge</div>
        </td>
        <td colspan='5' align='center'>
            <!--默认收起错误信息 -Findyou
            <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
            <div id='div_ft1_3' class="collapse">  -->
            <!-- 默认展开错误信息 -Findyou -->
            <button id='btn_ft1_3' type="button" class="btn btn-danger btn-xs" data-toggle="collapse"
                    data-target='#div_ft1_3'>错误
            </button>
            <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: ImportError: Failed to import test module: case_recharge
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\testcase\case_recharge.py", line 20, in &lt;module&gt;
    my_generate = Generate(file_path, sheet_name, yaml_file=f'{CONF_DIR}parms.yaml')
TypeError: __init__() got an unexpected keyword argument 'yaml_file'



    </pre>
            </div>
        </td>
    </tr>

    <tr id='ft1_4' class='none'>
        <td class='errorCase'>
            <div class='testcase'>case_withdraw</div>
        </td>
        <td colspan='5' align='center'>
            <!--默认收起错误信息 -Findyou
            <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
            <div id='div_ft1_4' class="collapse">  -->
            <!-- 默认展开错误信息 -Findyou -->
            <button id='btn_ft1_4' type="button" class="btn btn-danger btn-xs" data-toggle="collapse"
                    data-target='#div_ft1_4'>错误
            </button>
            <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: ImportError: Failed to import test module: case_withdraw
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\testcase\case_withdraw.py", line 20, in &lt;module&gt;
    my_generate = Generate(file_path, sheet_name, yaml_file=f'{CONF_DIR}parms.yaml')
TypeError: __init__() got an unexpected keyword argument 'yaml_file'



    </pre>
            </div>
        </td>
    </tr>

    <tr class='errorClass warning'>
        <td>case_login.LoginTestCase</td>
        <td class="text-center">4</td>
        <td class="text-center">0</td>
        <td class="text-center">0</td>
        <td class="text-center">4</td>
        <td class="text-center"><a href="javascript:showClassDetail('c2',4)" class="detail" id='c2'>详细</a></td>
    </tr>

    <tr id='ft2_1' class='none'>
        <td class='errorCase'>
            <div class='testcase'>testLogin_1_登陆成功</div>
        </td>
        <td colspan='5' align='center'>
            <!--默认收起错误信息 -Findyou
            <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
            <div id='div_ft2_1' class="collapse">  -->
            <!-- 默认展开错误信息 -Findyou -->
            <button id='btn_ft2_1' type="button" class="btn btn-danger btn-xs" data-toggle="collapse"
                    data-target='#div_ft2_1'>错误
            </button>
            <div id='div_ft2_1' class="collapse in" align="left">
    <pre>
    
ft2_1: 
-------------start--------------
--------------end---------------
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\library\ddt.py", line 154, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\testcase\case_login.py", line 49, in testLogin
    params=eval(case.request_data))
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\common\R_request.py", line 47, in request
    res = self.session.post(url=url, data=data, headers=headers, cookies=cookies, timeout=timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/member/login': No schema supplied. Perhaps you meant http:///member/login?


    </pre>
            </div>
        </td>
    </tr>

    <tr id='ft2_2' class='none'>
        <td class='errorCase'>
            <div class='testcase'>testLogin_2_登陆失败_手机号码为空</div>
        </td>
        <td colspan='5' align='center'>
            <!--默认收起错误信息 -Findyou
            <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
            <div id='div_ft2_2' class="collapse">  -->
            <!-- 默认展开错误信息 -Findyou -->
            <button id='btn_ft2_2' type="button" class="btn btn-danger btn-xs" data-toggle="collapse"
                    data-target='#div_ft2_2'>错误
            </button>
            <div id='div_ft2_2' class="collapse in" align="left">
    <pre>
    
ft2_2: 
-------------start--------------
--------------end---------------
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\library\ddt.py", line 154, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\testcase\case_login.py", line 49, in testLogin
    params=eval(case.request_data))
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\common\R_request.py", line 47, in request
    res = self.session.post(url=url, data=data, headers=headers, cookies=cookies, timeout=timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/member/login': No schema supplied. Perhaps you meant http:///member/login?


    </pre>
            </div>
        </td>
    </tr>

    <tr id='ft2_3' class='none'>
        <td class='errorCase'>
            <div class='testcase'>testLogin_3_登陆失败_密码为空</div>
        </td>
        <td colspan='5' align='center'>
            <!--默认收起错误信息 -Findyou
            <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
            <div id='div_ft2_3' class="collapse">  -->
            <!-- 默认展开错误信息 -Findyou -->
            <button id='btn_ft2_3' type="button" class="btn btn-danger btn-xs" data-toggle="collapse"
                    data-target='#div_ft2_3'>错误
            </button>
            <div id='div_ft2_3' class="collapse in" align="left">
    <pre>
    
ft2_3: 
-------------start--------------
--------------end---------------
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\library\ddt.py", line 154, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\testcase\case_login.py", line 49, in testLogin
    params=eval(case.request_data))
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\common\R_request.py", line 47, in request
    res = self.session.post(url=url, data=data, headers=headers, cookies=cookies, timeout=timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/member/login': No schema supplied. Perhaps you meant http:///member/login?


    </pre>
            </div>
        </td>
    </tr>

    <tr id='ft2_4' class='none'>
        <td class='errorCase'>
            <div class='testcase'>testLogin_4_登陆失败_用户名或者密码错误</div>
        </td>
        <td colspan='5' align='center'>
            <!--默认收起错误信息 -Findyou
            <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
            <div id='div_ft2_4' class="collapse">  -->
            <!-- 默认展开错误信息 -Findyou -->
            <button id='btn_ft2_4' type="button" class="btn btn-danger btn-xs" data-toggle="collapse"
                    data-target='#div_ft2_4'>错误
            </button>
            <div id='div_ft2_4' class="collapse in" align="left">
    <pre>
    
ft2_4: 
-------------start--------------
--------------end---------------
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\library\ddt.py", line 154, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\testcase\case_login.py", line 49, in testLogin
    params=eval(case.request_data))
  File "C:\Users\Administrator\PycharmProjects\keyou\package_301\common\R_request.py", line 47, in request
    res = self.session.post(url=url, data=data, headers=headers, cookies=cookies, timeout=timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/member/login': No schema supplied. Perhaps you meant http:///member/login?


    </pre>
            </div>
        </td>
    </tr>

    <tr id='total_row' class="text-center active">
        <td>总计</td>
        <td>8</td>
        <td>0</td>
        <td>0</td>
        <td>8</td>
        <td>通过率：0.00%</td>
    </tr>
</table>

<div id='ending'>&nbsp;</div>
<div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style="font-size:30px;" aria-hidden="true">
    </span></a></div>

</body>
</html>
